#!/bin/bash
trap "exit" INT

LOG_PATH="./days"
PAST=0

log(){
    CURR_DATE=`date +%Y-%m-%d`
    CURR_TIME=`date +%H:%M`

    echo -e "_${CURR_DATE} ${CURR_TIME}_\t${1}" >> "${LOG_PATH}${CURR_DATE}.log.md"
}

log_past(){
    timestamp=`(date +%s)`
    timestamp=`echo $((($timestamp)-(${1}*60)))`
    CURR_DATE=`date -r ${timestamp} +%Y-%m-%d`
    CURR_TIME=`date -r ${timestamp} +%H:%M`

    echo -e "_${CURR_DATE} ${CURR_TIME}_\t${2}" >> "${LOG_PATH}${CURR_DATE}.log.md"
}

finish(){
  if [ "$(uname)" == "Darwin" ]; then
    say -v Kate "${1}"
    terminal-notifier -message 'shPAGETTI'\
    -title "${1}"\
    -sound Crystal
  elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    say "${1}"
    notify-send "shPAGETTI" "${1}"
  #elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then
      # Do something under 32 bits Windows NT platform
  #elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then
      # Do something under 64 bits Windows NT platform
  fi
}

while :; do
    case $1 in
        -t|--time) TIME="$2"
        shift
        ;;
        -m|--message) MESSAGE="$2"
        shift
        ;;
        -l|--log) LOG_PATH="$2/"
        shift
        ;;
        -p|--past) PAST=1
        shift
        ;;
        *) break
    esac
    shift
done

if [ -z "$TIME" ]
then
    echo "How many rounds you want to do (minutes)?"
    read TIME
fi

START_MESSAGE="Timer(${TIME}m) started"
END_MESSAGE="Timer(${TIME}m) ended"

if [[ ! -e "${LOG_PATH}" ]]; then
    mkdir -p "${LOG_PATH}"
elif [[ ! -d "${LOG_PATH}" ]]; then
    echo "${LOG_PATH} already exists but is not a directory" 1>&2
fi

if [ $PAST -eq 1 ]
then
  if [ -z "$MESSAGE" ]
  then
      log "${START_MESSAGE}"
  else
      log "**${MESSAGE}**\t${START_MESSAGE}"
  fi
fi

if [ $PAST -eq 0 ]
then
  if [ -z "$MESSAGE" ]
  then
      log "${START_MESSAGE}"
  else
      log "**${MESSAGE}**\t${START_MESSAGE}"
  fi

  timer ${TIME}m && FINISHED="finished"
else
  FINISHED="finished"
  if [ -z "$MESSAGE" ]
  then
      log_past ${TIME} "${START_MESSAGE}"
  else
      log_past ${TIME} "**${MESSAGE}**\t${START_MESSAGE}"
  fi
fi

if [ ! -z "$FINISHED" ]
then
    if [ -z "$MESSAGE" ]
    then
        log "${END_MESSAGE}"
    else
        log "**${MESSAGE}**\t${END_MESSAGE}"
    fi

    finish "Work Timer is up! Take a Break."
else
    echo "What is the reason of termination?"
    read REASON
    log "Early termination with reason: **${REASON}**"
fi
